// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddSchedule(arg1:database.Schedule):Promise<void>;

export function DeleteSchedule(arg1:number):Promise<void>;

export function GetAllSystemInfo():Promise<any>;

export function GetCPUInfo():Promise<any>;

export function GetDiskInfo():Promise<any>;

export function GetGPUInfo():Promise<any>;

export function GetHardwareInfo():Promise<any>;

export function GetLocationInfo():Promise<any>;

export function GetMemoryInfo():Promise<any>;

export function GetOSInfo():Promise<any>;

export function GetUsagePercentages():Promise<any>;

export function ListSchedules():Promise<Array<database.Schedule>>;

export function SyncWithSystem():Promise<void>;

export function ToggleSchedule(arg1:number,arg2:boolean):Promise<void>;

export function UpdateSchedule(arg1:database.Schedule):Promise<void>;
