// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSchedule(arg1) {
  return window['go']['app']['App']['AddSchedule'](arg1);
}

export function DeleteSchedule(arg1) {
  return window['go']['app']['App']['DeleteSchedule'](arg1);
}

export function GetAllSystemInfo() {
  return window['go']['app']['App']['GetAllSystemInfo']();
}

export function GetCPUInfo() {
  return window['go']['app']['App']['GetCPUInfo']();
}

export function GetDiskInfo() {
  return window['go']['app']['App']['GetDiskInfo']();
}

export function GetGPUInfo() {
  return window['go']['app']['App']['GetGPUInfo']();
}

export function GetHardwareInfo() {
  return window['go']['app']['App']['GetHardwareInfo']();
}

export function GetLocationInfo() {
  return window['go']['app']['App']['GetLocationInfo']();
}

export function GetMemoryInfo() {
  return window['go']['app']['App']['GetMemoryInfo']();
}

export function GetOSInfo() {
  return window['go']['app']['App']['GetOSInfo']();
}

export function GetUsagePercentages() {
  return window['go']['app']['App']['GetUsagePercentages']();
}

export function ListSchedules() {
  return window['go']['app']['App']['ListSchedules']();
}

export function SyncWithSystem() {
  return window['go']['app']['App']['SyncWithSystem']();
}

export function ToggleSchedule(arg1, arg2) {
  return window['go']['app']['App']['ToggleSchedule'](arg1, arg2);
}

export function UpdateSchedule(arg1) {
  return window['go']['app']['App']['UpdateSchedule'](arg1);
}
