// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/cpu": {
            "get": {
                "description": "Retrieve detailed CPU information including cores, frequency, and usage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cpu"
                ],
                "summary": "Get CPU information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CPUInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/disk": {
            "get": {
                "description": "Retrieve disk information including partitions, usage, and I/O statistics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "disk"
                ],
                "summary": "Get disk information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DiskInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/gpu": {
            "get": {
                "description": "Retrieve GPU information including model, memory, and driver details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gpu"
                ],
                "summary": "Get GPU information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GPUInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hardware": {
            "get": {
                "description": "Retrieve hardware information including motherboard, BIOS, and device details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hardware"
                ],
                "summary": "Get hardware information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HardwareInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/location": {
            "get": {
                "description": "Retrieve system location information including timezone and locale",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get location information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LocationInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/memory": {
            "get": {
                "description": "Retrieve memory information including total, used, and available memory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "memory"
                ],
                "summary": "Get memory information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MemoryInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/os": {
            "get": {
                "description": "Retrieve operating system information including name, version, and architecture",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "os"
                ],
                "summary": "Get OS information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OSInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/schedules": {
            "get": {
                "description": "Retrieve a list of all schedules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "List all schedules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new schedule with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Add a new schedule",
                "parameters": [
                    {
                        "description": "Schedule details",
                        "name": "schedule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.Schedule"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/schedules/sync": {
            "post": {
                "description": "Manually trigger synchronization with the system scheduler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Sync with system scheduler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/schedules/{id}": {
            "get": {
                "description": "Retrieve a specific schedule by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Get a schedule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing schedule by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Update a schedule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated schedule details",
                        "name": "schedule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/database.Schedule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a schedule by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Delete a schedule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/schedules/{id}/toggle": {
            "patch": {
                "description": "Enable or disable a schedule by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "Toggle a schedule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Enable/disable flag",
                        "name": "enabled",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "enabled": {
                                    "type": "boolean"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/system": {
            "get": {
                "description": "Retrieve comprehensive system information including CPU, GPU, memory, disk, and hardware details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get all system information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SystemInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/test": {
            "get": {
                "description": "A flexible endpoint for testing custom methods and logic",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "summary": "Test route for personal methods",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/usage": {
            "get": {
                "description": "Retrieve usage percentages for CPU, GPU, memory, and disk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "usage"
                ],
                "summary": "Get usage percentages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UsagePercentages"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API is running and healthy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.Schedule": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "repeat_pattern": {
                    "description": "once, daily, weekly",
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.APIResponse": {
            "description": "Standard API response structure",
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string",
                    "example": "System benchmark API is running"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "models.CPU": {
            "description": "CPU information including cores, model, cache, frequency, and usage",
            "type": "object",
            "properties": {
                "cache_size": {
                    "type": "string",
                    "example": "8MB"
                },
                "cores": {
                    "type": "integer",
                    "example": 8
                },
                "cpu_usage_percentage": {
                    "type": "string",
                    "example": "45.2%"
                },
                "ghz": {
                    "type": "string",
                    "example": "3.2GHz"
                },
                "model": {
                    "type": "string",
                    "example": "Intel Core i7-10700K"
                }
            }
        },
        "models.CPUInfo": {
            "description": "CPU information including cores, model, cache, frequency, and usage",
            "type": "object",
            "properties": {
                "cache_size": {
                    "type": "string",
                    "example": "8MB"
                },
                "cores": {
                    "type": "integer",
                    "example": 8
                },
                "cpu_usage_percentage": {
                    "type": "string",
                    "example": "45.2%"
                },
                "ghz": {
                    "type": "string",
                    "example": "3.2GHz"
                },
                "model": {
                    "type": "string",
                    "example": "Intel Core i7-10700K"
                }
            }
        },
        "models.Disk": {
            "description": "Disk information including total, used, free, and usage percentage",
            "type": "object",
            "properties": {
                "free": {
                    "type": "string",
                    "example": "500GB"
                },
                "total": {
                    "type": "string",
                    "example": "1TB"
                },
                "used": {
                    "type": "string",
                    "example": "500GB"
                },
                "used_percentage": {
                    "type": "string",
                    "example": "50%"
                }
            }
        },
        "models.DiskInfo": {
            "description": "Disk information including total, used, free, and usage percentage",
            "type": "object",
            "properties": {
                "free": {
                    "type": "string",
                    "example": "500GB"
                },
                "total": {
                    "type": "string",
                    "example": "1TB"
                },
                "used": {
                    "type": "string",
                    "example": "500GB"
                },
                "used_percentage": {
                    "type": "string",
                    "example": "50%"
                }
            }
        },
        "models.ErrorResponse": {
            "description": "Error response structure",
            "type": "object",
            "properties": {
                "details": {
                    "type": "string",
                    "example": "connection timeout"
                },
                "error": {
                    "type": "string",
                    "example": "Failed to get system information"
                }
            }
        },
        "models.GPU": {
            "description": "GPU information including name, VRAM, driver, usage, and clock speed",
            "type": "object",
            "properties": {
                "clock_speed": {
                    "type": "string",
                    "example": "1800MHz"
                },
                "driver": {
                    "type": "string",
                    "example": "470.82.01"
                },
                "name": {
                    "type": "string",
                    "example": "NVIDIA GeForce RTX 3080"
                },
                "usage_percentage": {
                    "type": "string",
                    "example": "30%"
                },
                "vram_size": {
                    "type": "string",
                    "example": "10GB"
                }
            }
        },
        "models.GPUInfo": {
            "description": "GPU information including name, VRAM, driver, usage, and clock speed",
            "type": "object",
            "properties": {
                "clock_speed": {
                    "type": "string",
                    "example": "1800MHz"
                },
                "driver": {
                    "type": "string",
                    "example": "470.82.01"
                },
                "name": {
                    "type": "string",
                    "example": "NVIDIA GeForce RTX 3080"
                },
                "usage_percentage": {
                    "type": "string",
                    "example": "30%"
                },
                "vram_size": {
                    "type": "string",
                    "example": "10GB"
                }
            }
        },
        "models.HardwareInfo": {
            "description": "Hardware/network interface information including index, MTU, name, hardware address, and flags",
            "type": "object",
            "properties": {
                "flags": {
                    "type": "string",
                    "example": "up,broadcast,running,multicast"
                },
                "hardware_addr": {
                    "type": "string",
                    "example": "00:11:22:33:44:55"
                },
                "index": {
                    "type": "integer",
                    "example": 1
                },
                "mtu": {
                    "type": "integer",
                    "example": 1500
                },
                "name": {
                    "type": "string",
                    "example": "eth0"
                }
            }
        },
        "models.Location": {
            "description": "Location information including IP, hostname, city, region, country, and timezone",
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "San Francisco"
                },
                "country": {
                    "type": "string",
                    "example": "US"
                },
                "hostname": {
                    "type": "string",
                    "example": "my-server"
                },
                "ip": {
                    "type": "string",
                    "example": "192.168.1.100"
                },
                "loc": {
                    "type": "string",
                    "example": "37.7749,-122.4194"
                },
                "org": {
                    "type": "string",
                    "example": "AS1234 Example Corp"
                },
                "postal": {
                    "type": "string",
                    "example": "94105"
                },
                "readme": {
                    "type": "string",
                    "example": "https://ipinfo.io/missingauth"
                },
                "region": {
                    "type": "string",
                    "example": "California"
                },
                "timezone": {
                    "type": "string",
                    "example": "America/Los_Angeles"
                }
            }
        },
        "models.LocationInfo": {
            "description": "Location information including IP, hostname, city, region, country, and timezone",
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "San Francisco"
                },
                "country": {
                    "type": "string",
                    "example": "US"
                },
                "hostname": {
                    "type": "string",
                    "example": "my-server"
                },
                "ip": {
                    "type": "string",
                    "example": "192.168.1.100"
                },
                "loc": {
                    "type": "string",
                    "example": "37.7749,-122.4194"
                },
                "org": {
                    "type": "string",
                    "example": "AS1234 Example Corp"
                },
                "postal": {
                    "type": "string",
                    "example": "94105"
                },
                "readme": {
                    "type": "string",
                    "example": "https://ipinfo.io/missingauth"
                },
                "region": {
                    "type": "string",
                    "example": "California"
                },
                "timezone": {
                    "type": "string",
                    "example": "America/Los_Angeles"
                }
            }
        },
        "models.Memory": {
            "description": "Memory information including total, used, free, available, and usage percentage",
            "type": "object",
            "properties": {
                "available": {
                    "type": "string",
                    "example": "12GB"
                },
                "free": {
                    "type": "string",
                    "example": "4GB"
                },
                "total": {
                    "type": "string",
                    "example": "16GB"
                },
                "used": {
                    "type": "string",
                    "example": "8GB"
                },
                "used_percentage": {
                    "type": "string",
                    "example": "50%"
                }
            }
        },
        "models.MemoryInfo": {
            "description": "Memory information including total, used, free, available, and usage percentage",
            "type": "object",
            "properties": {
                "available": {
                    "type": "string",
                    "example": "12GB"
                },
                "free": {
                    "type": "string",
                    "example": "4GB"
                },
                "total": {
                    "type": "string",
                    "example": "16GB"
                },
                "used": {
                    "type": "string",
                    "example": "8GB"
                },
                "used_percentage": {
                    "type": "string",
                    "example": "50%"
                }
            }
        },
        "models.OS": {
            "description": "Operating system information including name, hostname, platform, version, and uptime",
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string",
                    "example": "my-server"
                },
                "kernel_arch": {
                    "type": "string",
                    "example": "x86_64"
                },
                "kernel_version": {
                    "type": "string",
                    "example": "5.4.0-74-generic"
                },
                "os": {
                    "type": "string",
                    "example": "linux"
                },
                "platform": {
                    "type": "string",
                    "example": "ubuntu"
                },
                "platform_family": {
                    "type": "string",
                    "example": "debian"
                },
                "platform_version": {
                    "type": "string",
                    "example": "20.04.3 LTS"
                },
                "uptime": {
                    "type": "integer",
                    "example": 86400
                }
            }
        },
        "models.OSInfo": {
            "description": "Operating system information including name, hostname, platform, version, and uptime",
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string",
                    "example": "my-server"
                },
                "kernel_arch": {
                    "type": "string",
                    "example": "x86_64"
                },
                "kernel_version": {
                    "type": "string",
                    "example": "5.4.0-74-generic"
                },
                "os": {
                    "type": "string",
                    "example": "linux"
                },
                "platform": {
                    "type": "string",
                    "example": "ubuntu"
                },
                "platform_family": {
                    "type": "string",
                    "example": "debian"
                },
                "platform_version": {
                    "type": "string",
                    "example": "20.04.3 LTS"
                },
                "uptime": {
                    "type": "integer",
                    "example": 86400
                }
            }
        },
        "models.SystemInfo": {
            "description": "Complete system information response containing all system details",
            "type": "object",
            "properties": {
                "cpu": {
                    "$ref": "#/definitions/models.CPU"
                },
                "disk": {
                    "$ref": "#/definitions/models.Disk"
                },
                "gpus": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GPU"
                    }
                },
                "hardware": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.HardwareInfo"
                    }
                },
                "location": {
                    "$ref": "#/definitions/models.Location"
                },
                "memory": {
                    "$ref": "#/definitions/models.Memory"
                },
                "os": {
                    "$ref": "#/definitions/models.OS"
                }
            }
        },
        "models.UsagePercentages": {
            "description": "Usage percentages for CPU, GPU, memory, and disk",
            "type": "object",
            "properties": {
                "cpu_usage": {
                    "type": "string",
                    "example": "45.2%"
                },
                "disk_usage": {
                    "type": "string",
                    "example": "75%"
                },
                "gpu_usage": {
                    "type": "string",
                    "example": "30%"
                },
                "memory_usage": {
                    "type": "string",
                    "example": "50%"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "System Benchmark API",
	Description:      "A comprehensive API for retrieving system information including CPU, GPU, memory, disk, and hardware details.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
