// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllSystemInfo():Promise<any>;

export function GetCPUInfo():Promise<any>;

export function GetDiskInfo():Promise<any>;

export function GetGPUInfo():Promise<any>;

export function GetHardwareInfo():Promise<any>;

export function GetLocationInfo():Promise<any>;

export function GetMemoryInfo():Promise<any>;

export function GetOSInfo():Promise<any>;

export function GetUsagePercentages():Promise<any>;
